### ISSUE TITLE
How to remove popup window while running code

### ISSUE THREAD

**Issue by Rad-Sroud333** [Utkarsh-Deshmukh/Single-Image-Dehazing-Python#5] opened 2023-02-05 15:21 UTC
There is always a popup window when we run code for every single image how to resolve it?

**Comment by Utkarsh-Deshmukh** [comment] 2023-02-05 15:28
Do you mean the windows which display the output?

**Comment by Rad-Sroud333** [comment] 2023-02-05 15:31
Like I am running code on image by giving path then first it shows popup
window then for getting dehaze-image or it's array we have to cancel that popup window then it will
run further code and return array or show image

**Comment by Utkarsh-Deshmukh** [comment] 2023-02-05 15:36
Let me take a look at it.

**Comment by Rad-Sroud333** [comment] 2023-02-05 15:39
Thanks

**Comment by Utkarsh-Deshmukh** [comment] 2023-02-05 21:35
@Rad-Sroud333 the issue is now fixed. The pop window used to display the Haze Transmission Map. There is now an option to avoid displaying this map. you will need to reinstall the image-dehazer library using the command: `pip install image-dehazer --upgrade`

In your script, you can then use a syntax like this:
`HazeCorrectedImg = image_dehazer.remove_haze(HazeImg, showHazeTrasmissionMap=False)`

**Closed as completed** 2023-02-05 21:36 UTC
